[package]
name = "fujisaki_ringsig"
version = "0.0.1"
authors = ["Michael Rosenberg <42micro@gmail.com>"]
license = "MIT OR Apache-2.0"

description = "Fujisaki-Suzuki Ring Signatures in Rust"
keywords = ["ring", "signature", "crypto", "cryptography"]
repository = "https://github.com/doomrobo/fujisaki-ringsig"

[dependencies]
rand = "0.3"
generic-array = "0.8"
digest = "0.6"
blake2 = "0.6"

[dependencies.curve25519-dalek]
version = "0.9"
features = ["yolocrypto"] # So we can use decaf and its elligator impl
