[package]
name = "fujisaki_ringsig"
version = "0.0.3"
authors = ["Michael Rosenberg <micro@fastmail.com>"]
license = "MIT OR Apache-2.0"

description = "Fujisaki-Suzuki Ring Signatures in Rust"
keywords = ["ring", "signature", "crypto", "cryptography"]
repository = "https://github.com/rozbb/fujisaki-ringsig"
documentation = "https://docs.rs/fujisaki_ringsig"

[dependencies]
blake2 = "0.6"
curve25519-dalek = "0.13"
digest = "0.6"
generic-array = "0.9"
rand = "0.3"
